services:
  springboot-kafka:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.otel-instrument
    container_name: springboot-kafka
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - ./values.env
    networks:
      - otel-demo

networks:
  otel-demo:
    external: true
