receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318


processors:
  batch: null

exporters:

  debug:
    verbosity: detailed

  kafka/applogs:
    brokers:
      - 'kafka:9092'
    encoding: otlp_json
    protocol_version: 3.7.0
    topic: applogs

  kafka/apptraces:
    brokers:
      - 'kafka:9092'
    encoding: otlp_json
    protocol_version: 3.7.0
    topic: apptraces

  kafka/appmetrics:
    brokers:
      - 'kafka:9092'
    encoding: otlp_json
    protocol_version: 3.7.0
    topic: appmetrics


  prometheus:
    endpoint: "0.0.0.0:9090"
    resource_to_telemetry_conversion:
      enabled: true

  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true

  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: http://loki:3100/otlp

service:
  pipelines:

    logs:
      exporters: [debug, kafka/applogs, otlphttp/loki]
      processors: [batch]
      receivers: [otlp]

    traces:
      exporters: [debug, kafka/apptraces, otlp/jaeger, otlp/tempo]
      processors: [batch]
      receivers: [otlp]

    metrics:
      exporters: [debug, kafka/appmetrics, prometheus]
      processors: [batch]
      receivers: [otlp]
