receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318


processors:
  batch: null

exporters:

  debug:
    verbosity: detailed

  kafka/logs:
    brokers:
      - 'kafka:9092'
    encoding: otlp_json
    protocol_version: 3.7.0
    topic: apmlogs

  kafka/metrics:
    brokers:
      - 'kafka:9092'
    encoding: otlp_json
    protocol_version: 3.7.0
    topic: apmmetrics

  kafka/traces:
    brokers:
      - 'kafka:9092'
    encoding: otlp_json
    protocol_version: 3.7.0
    topic: apmtraces

  prometheus:
    endpoint: "0.0.0.0:9090"
    resource_to_telemetry_conversion:
      enabled: true

  otlp:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
    
service:
  pipelines:

    logs:
      exporters: [debug, kafka/logs]
      processors: [batch]
      receivers: [otlp]

    traces:
      exporters: [debug, kafka/traces]
      processors: [batch]
      receivers: [otlp]

    metrics:
      exporters: [debug, kafka/metrics, prometheus]
      processors: [batch]
      receivers: [otlp]