# x-logging:
#   &default-logging
#   driver: "json-file"
#   options:
#     max-size: "1m"
#     max-file: "1"
#     tag: "{{.Name}}"

services:
  springboot-todo:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.otel-instrument
    container_name: springboot-todo
    restart: always
    ports:
      - "8082:8080"
    env_file:
      - ./values.env
    networks:
      - otel-demo
    # logging: *default-logging

networks:
  otel-demo:
    external: true
