FROM registry.access.redhat.com/ubi9/openjdk-21:1.21

ARG OTEL_JAVA_INSTRUMENT_JAR_VER=v2.16.0

ENV LANGUAGE='en_US:en'

COPY --chown=185 ../otel-agents/javaagent-otel-${OTEL_JAVA_INSTRUMENT_JAR_VER}.jar /deployments/javaagent-otel-${OTEL_JAVA_INSTRUMENT_JAR_VER}.jar


COPY --chown=185 ../target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 ../target/quarkus-app/*.jar /deployments/
COPY --chown=185 ../target/quarkus-app/app/ /deployments/app/
COPY --chown=185 ../target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENV OTEL_URL="http://otelcol:4318"
ENV OTLP_PROTOCOL="otlp"
ENV SAMPLE_APP_NAME=quakrus-todo-postgres
ENV JAVA_OPTS_APPEND="-javaagent:./javaagent-otel-${OTEL_JAVA_INSTRUMENT_JAR_VER}.jar -Dotel.service.name=${SAMPLE_APP_NAME} -Dotel.exporter.otlp.endpoint=${OTEL_URL} -Dotel.traces.exporter=${OTLP_PROTOCOL} -Dotel.metrics.exporter=${OTLP_PROTOCOL} -Dotel.logs.exporter=${OTLP_PROTOCOL} -Dotel.resource.attributes=service.name=${SAMPLE_APP_NAME} -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
