# x-logging: &default-logging
#   driver: "journald"
#   options:
#     max-size: "1m"
#     max-file: "1"
#     tag: "{{.Name}}"

services:
  quakrus-todo-postgres:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.otel-instrument-jvm
    container_name: quakrus-todo-postgres
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - ./values.env
    networks:
      - otel-demo
    # logging: *default-logging

networks:
  otel-demo:
    external: true
